import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bell, ShieldAlert, AlertTriangle, Info, Check, Eye } from 'lucide-react';
import DashboardLayout from '../layouts/DashboardLayout';
import PageHeader from '../components/layout/PageHeader';
import Card from '../components/common/Card';
import Badge from '../components/common/Badge';
import Button from '../components/common/Button';
import Loader from '../components/common/Loader';
import { getAlerts } from '../services/api';

const Alerts = () => {
  const navigate = useNavigate();
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterSeverity, setFilterSeverity] = useState('ALL');

  useEffect(() => {
    const fetchAlertsData = async () => {
      setLoading(true);
      try {
        const data = await getAlerts();
        setAlerts(data);
        setLoading(false);
      } catch (err) {
        console.error('Failed to load alerts:', err);
        setLoading(false);
      }
    };
    fetchAlertsData();
  }, []);

  const filteredAlerts = filterSeverity === 'ALL'
    ? alerts
    : alerts.filter(a => a.severity === filterSeverity);

  return (
    <DashboardLayout>
      <PageHeader
        title="Security System Alerts & Threat Feed"
        subtitle="Real-time notifications generated by automated multi-layer document screening modules."
        badge={<Badge variant="warning">{alerts.length} Active Alerts</Badge>}
      />

      <Card className="mb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Severity Filter:</span>
            <div className="flex items-center gap-1.5 bg-slate-950 p-1 rounded-lg border border-slate-800">
              {['ALL', 'HIGH', 'MEDIUM', 'LOW'].map((sev) => (
                <button
                  key={sev}
                  type="button"
                  onClick={() => setFilterSeverity(sev)}
                  className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                    filterSeverity === sev
                      ? 'bg-blue-600 text-white shadow'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {sev}
                </button>
              ))}
            </div>
          </div>

          <Button
            variant="ghost"
            size="sm"
            icon={Check}
            onClick={() => setAlerts([])}
          >
            Clear All Alerts
          </Button>
        </div>
      </Card>

      {loading ? (
        <Loader text="Fetching security alert feed..." />
      ) : filteredAlerts.length === 0 ? (
        <Card className="text-center p-8">
          <Bell className="w-10 h-10 text-slate-500 mx-auto mb-2" />
          <h3 className="text-sm font-bold text-slate-200">No Security Alerts Found</h3>
          <p className="text-xs text-slate-400 mt-1">All screening modules operating within normal parameters.</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {filteredAlerts.map((item) => (
            <Card
              key={item.id}
              className={`transition-all ${
                item.severity === 'HIGH'
                  ? 'border-l-4 border-l-rose-500 bg-slate-900/90'
                  : 'border-l-4 border-l-amber-500 bg-slate-900/90'
              }`}
            >
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div className="flex items-start gap-3.5">
                  <div
                    className={`p-2.5 rounded-xl border shrink-0 ${
                      item.severity === 'HIGH'
                        ? 'bg-rose-500/20 text-rose-400 border-rose-500/40'
                        : 'bg-amber-500/20 text-amber-400 border-amber-500/40'
                    }`}
                  >
                    {item.severity === 'HIGH' ? (
                      <ShieldAlert className="w-5 h-5" />
                    ) : (
                      <AlertTriangle className="w-5 h-5" />
                    )}
                  </div>

                  <div>
                    <div className="flex items-center gap-2">
                      <h4 className="text-xs font-bold text-slate-100">{item.title}</h4>
                      <Badge
                        variant={item.severity === 'HIGH' ? 'high_risk' : 'warning'}
                        size="sm"
                      >
                        {item.severity} SEVERITY
                      </Badge>
                    </div>
                    <p className="text-xs text-slate-300 mt-1">{item.description}</p>
                    <div className="mt-2 flex items-center gap-3 text-[11px] font-mono text-slate-400">
                      <span>Document ID: #{item.documentId}</span>
                      <span>•</span>
                      <span>Time: {item.time}</span>
                    </div>
                  </div>
                </div>

                <Button
                  variant="outline"
                  size="sm"
                  icon={Eye}
                  onClick={() => navigate(`/verification-result?id=${item.documentId}`)}
                  className="shrink-0"
                >
                  View Case
                </Button>
              </div>
            </Card>
          ))}
        </div>
      )}
    </DashboardLayout>
  );
};

export default Alerts;
